name: Deploy Application Youtube

on:
  push:
    branches: [main]

jobs:
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull kiriyobr/deploy_ghactions:latest
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name deploy_ghactions kiriyobr/deploy_ghactions
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Login DockerHub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Build docker image
        run: docker build -t kiriyobr/deploy_ghactions .

      - name: Push image docker
        run: docker push kiriyobr/deploy_ghactions
